---
- name: install AD-Domain-Services
  win_feature:
    name: AD-Domain-Services
    state: present

- name: setup ad controller
  win_domain:
    dns_domain_name: "ad1.{{ guid }}.example.opentlc.com"
    safe_mode_password:  "{{ ad_safe_mode_password }}"
  register: ad_setup

- name: reboot ad server
  win_reboot:
    reboot_timeout: 1800
  when: ad_setup.reboot_required

- name: print out domain list
  win_shell: "nltest /dclist:{{ ad_domain_name }}"
  register: domain_list

- name: list configured domains
  debug:
    var: domain_list.stdout_lines
